### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by amartinwest** [rlancaste/KStars-INDI-Mac-Dev#1]
Thank you for this massive development, been hunting around for mac development env for this for a a few weeks. I have run into a few problems.

Had tons of compilation errors on the Third Party stuff, so I nooped that but then had to correct  setup.sh

[notes.txt](https://github.com/rlancaste/KStars-INDI-Mac-Dev/files/6085712/notes.txt)

build console log

[build-log.txt](https://github.com/rlancaste/KStars-INDI-Mac-Dev/files/6085768/build-log.txt)

**Comment by rlancaste** [comment]
Hi there, thanks for playing around with it.  So I noticed that you mentioned that you wrote a separate script so you wouldn't have to modify build-env.sh, but I don't understand because I designed the build-env file for you to use, you are supposed to modify it to match your setup.

Second, I noticed that INDI failed to build which then probably led to the later failures.  INDI is extremely important to the functioning of KStars and should really be installed and built before it continues.  It says the following:

-- The following OPTIONAL packages have been found:

 * PkgConfig
 * OggTheora

But then later said this: 

file not found
#include <theora/theoraenc.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.

So do you or don't you have ogg theora installed?  If it is not installed properly, I would probably recommend removing it since it is optional and the failure to find its files brought down your build.  I don't actually have it installed on my Kstars-INDI-Mac-Dev folders nor do I have it in homebrew, but I do have it in my craft build folder for building OS X dmgs.  If it is installed properly, we should look at why it didn't find it.

**Comment by rlancaste** [comment]
For the later problem, where it couldn't find the KDoctools catalogs, can you confirm for me if there was a symlink created in ~/Library/Application Support called kf5 that links to the KStars-INDI-Mac-Dev/ASTRO-ROOT/share/kf5 folder?

**Comment by amartinwest** [comment]
OK, to cut a long story short, I had an antiquated copy macports which was were oggtheoras was residing. Not sure why the include path didnt work. I have removed macports now. The reason for kf5 problems was that I had moved the original git download into an eclipse workspace but after I done an initial build so all the links were pointing to the original location DOH.  I started from scratch again and its has built.

I did download theora source but it didnt compile because of error in the png example.

The rationale for my run-setup script - My reasoning was that the build-env.sh is on git and might be overwritten, it is quite large and the modifiable elements are some way into the script.
Im not a fan of git, much prefer subversion.

Thanks, now back to what I was trying to do.

**Comment by amartinwest** [comment]
PS meant to mention that home-brew downloads Qt6 by default now and installing Qt5 doesnt symlink so you have to manually symlink it.

**Comment by rlancaste** [comment]
I am not actually using the qt in home brew.  I am downloading it from qt so I have more control.  But I will say that dmg is built by whatever qt version  craft is currently using

**Comment by rlancaste** [comment]
The home brew qt used to be very very annoying to install.  It took forever
